comment:
    layout: "newheader, reach, diff, flags, files, newfooter"
    behavior: default
    hide_comment_details: true
    require_changes: false
    branches:
        - develop
        - main

coverage:
    status:
        patch: false
        project:
            default:
                target: auto
                threshold: 70%
