comment:
    layout: "reach, diff, flags, files"
    behavior: default
    require_changes: false
    branches:
        - develop
        - main

coverage:
    status:
        patch: false
        project:
            default:
                target: auto
                threshold: 70%
