comment:
    behavior: default
    require_changes: false
    branches:
        - develop
        - main

coverage:
    status:
        patch:
            default:
                target: auto
                threshold: 0.1%
        project:
            default:
                target: auto
                threshold: 70%
