name: mealkitary main ci

on:
    push:
        branches:
            - 'main'

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: JDK 11 구성
                uses: actions/setup-java@v3
                with:
                    java-version: '11'
                    distribution: 'temurin'
                    cache: 'gradle'

            -   name: Gradlew wrapper 실행 권한 부여
                run: chmod +x gradlew

            -   name: Gradle 캐싱
                uses: actions/cache@v3
                with:
                    path: |
                        ~/.gradle/caches
                        ~/.gradle/wrapper
                    key: ${{ runner.os }}-gradle-${{ hasFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                    restore-keys: |
                        ${{ runner.os }}-gradle-

            -   name: Gradle 빌드
                run: ./gradlew clean build

            -   name: Docker 로그인
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            -   name: 도커 이미지 빌드, 레지스트리 전송
                run: ./gradlew jib
