name: Jacoco Code Coverage & Test Result workflow

permissions:
    checks: write
    pull-requests: write

on:
    push:
        branches:
            - 'develop'
            - 'main'
    pull_request:
        branches:
            - 'develop'
            - 'main'

jobs:
    code-coverage:
        if: ${{ contains(github.event.*.labels.*.name, '테스트') }}
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: JDK 11 구성
                uses: actions/setup-java@v3
                with:
                    java-version: '11'
                    distribution: 'temurin'
                    cache: 'gradle'

            -   name: Gradlew wrapper 실행 권한 부여
                run: chmod +x gradlew
            -   name: Gradle 테스트
                run: ./gradlew test

            -   name: 테스트 결과 출력
                uses: EnricoMi/publish-unit-test-result-action@v2
                if: ${{ always() }}
                with:
                    files: |
                        ./mealkitary-api/build/test-results/**/*.xml
                        ./mealkitary-domain/build/test-results/**/*.xml

            -   name: Jacoco Coverage 리포트 전송
                uses: codecov/codecov-action@v3
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
                    files: ./mealkitary-api/build/reports/jacoco/test/jacocoTestReport.xml,./mealkitary-domain/build/reports/jacoco/test/jacocoTestReport.xml
                    name: mealkitary-codecov
                    verbose: true
