name: Mealkitary main, develop CI

permissions:
    contents: write
    pull-requests: write
    checks: write

on:
    pull_request:
        branches:
            - 'develop'
            - 'main'

jobs:
    gradle-task-codecov:
        if: ${{ contains(github.event.*.labels.*.name, format('run{0} ci', ':')) }}
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Firebase 시크릿 생성
                run: |
                    echo ${{ secrets.ENCODED_FIREBASE_JSON }} | base64 -d > ./mealkitary-infrastructure/adapter-firebase-notification/src/main/resources/firebase.json
            -   name: JDK 11 구성
                uses: actions/setup-java@v3
                with:
                    java-version: '11'
                    distribution: 'temurin'
                    cache: 'gradle'

            -   name: Gradlew wrapper 실행 권한 부여
                run: chmod +x gradlew

            -   name: Gradle 캐싱
                uses: actions/cache@v3
                with:
                    path: |
                        ~/.gradle/caches
                        ~/.gradle/wrapper
                    key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                    restore-keys: |
                        ${{ runner.os }}-gradle-

            -   name: Gradle 빌드
                run: ./gradlew clean build --exclude-task asciidoctor

            -   name: 테스트 결과 출력
                uses: EnricoMi/publish-unit-test-result-action@v2
                if: ${{ always() }}
                with:
                    files: |
                        ./mealkitary-api/build/test-results/**/*.xml
                        ./mealkitary-domain/build/test-results/**/*.xml
                        ./mealkitary-application/build/test-results/**/*.xml
                        ./mealkitary-infrastructure/adapter-persistence-spring-data-jpa/build/test-results/**/*.xml
                        ./mealkitary-infrastructure/adapter-paymentgateway-tosspayments/build/test-results/**/*.xml
                        ./mealkitary-infrastructure/adapter-firebase-notification/build/test-results/**/*.xml

            -   name: Jacoco Coverage 리포트 전송
                uses: codecov/codecov-action@v3
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
                    files: |
                        ./mealkitary-api/build/reports/jacoco/test/jacocoTestReport.xml,
                        ./mealkitary-domain/build/reports/jacoco/test/jacocoTestReport.xml,
                        ./mealkitary-application/build/reports/jacoco/test/jacocoTestReport.xml,
                        ./mealkitary-infrastructure/adapter-persistence-spring-data-jpa/build/reports/jacoco/test/jacocoTestReport.xml,
                        ./mealkitary-infrastructure/adapter-paymentgateway-tosspayments/build/reports/jacoco/test/jacocoTestReport.xml,
                        ./mealkitary-infrastructure/adapter-firebase-notification/build/reports/jacoco/test/jacocoTestReport.xml
                    name: mealkitary-codecov
                    verbose: true

    qodana:
        if: ${{ contains(github.event.*.labels.*.name, format('run{0} ci', ':')) }}
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
                with:
                    ref: ${{ github.event.pull_request.head.sha }}
                    fetch-depth: 0
            -   name: Qodana 정적 코드 분석 수행
                uses: JetBrains/qodana-action@v2023.2
                env:
                    QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
