name: Mealkitary Code Review Automation

permissions:
    contents: read
    pull-requests: write

on:
    pull_request:
        types: [ opened, reopened, synchronize ]

jobs:
    gpt-code-review:
        if: ${{ contains(github.event.*.labels.*.name, format('run{0} gpt code review', ':')) }}
        runs-on: ubuntu-latest
        steps:
            -   uses: anc95/ChatGPT-CodeReview@main
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                    LANGUAGE: Korean
                    OPENAI_API_ENDPOINT: https://api.openai.com/v1
                    MODEL: gpt-3.5-turbo
                    top_p: 1
                    temperature: 1
